version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api  # Dockerfile específico para el API
    ports:
      - "8000:8000"
    volumes:
      - models_volume:/app/models
    # Inicia el servidor FastAPI con uvicorn
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter  # Dockerfile para el entorno de desarrollo con JupyterLab
    ports:
      - "8888:8888"
    volumes:
      - models_volume:/app/models
    # Inicia JupyterLab
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  models_volume:
